### ISSUE TITLE
Need 1.6 Release

### ISSUE THREAD

**Issue by ngallaher** [sphinx-contrib/httpdomain#1]
Commit  81ab0e0 fixed https://bitbucket.org/birkenfeld/sphinx-contrib/pull-requests/152/fix-182-by-moving-around-initialization/diff, which is a release breaking bug preventing the use of `autohttp.flask`
A release with this fix would be much apprectiated.

**Comment by ngallaher** [comment]
I can PR an update to the changelog, but I'm imagining that's not particularly helpful.  If the maintainers can let me know what's most useful, I'm happy to do the needful.

**Comment by dahlia** [comment]
Released 1.6.0, finally.

<https://pypi.org/project/sphinxcontrib-httpdomain/1.6.0/>
