### ISSUE TITLE
Look for a new maintainer

### ISSUE THREAD

**Issue by dahlia** [sphinx-contrib/httpdomain#35]
Since I recently have no much chance to use Python at all, it's getting less motivating me to maintain this project.  If someone who wish maintain this project from now on, I would like to give them all necessary accesses (this repository, PyPI, & RTD.org).  No special prerequisites, but it would be great if them have experience of developing any Sphinx extensions or sending patches to this project.

**Comment by robertdzeigler** [comment]
Hi Dahlia, we use httpdomain (specifically the tornado piece) at our organization and I might be interested in taking over as maintainer.

**Comment by dahlia** [comment]
@robertdzeigler Thanks for helping us!  Let me know your PyPI and ReadTheDocs.org accounts (please create one if you don't have yet).  I'm going to give you accesses.

**Comment by ashb** [comment]
@dahlia I would also like to help out, as we use this domain on apache/airflow. I am `ashb` on both pypi and RTD. (We've got our own "custom" domains in apache/airflow, but I've not contributed to this extension before -- it's all just worked for me previously 😁)

**Comment by dahlia** [comment]
@ashb I've just give you the accessed on this repo, PyPI, & RTD.org.  Please check your inbox!  If everything seems well please close this issue too.  Thanks!

**Comment by ashb** [comment]
All good!

**Comment by ashb** [comment]
@oturpe Oop yes, thank you for the reminder!
