### ISSUE TITLE
Parallel builds throw (incorrect  ?) warnings

### ISSUE THREAD

**Issue by phlax** [sphinx-contrib/httpdomain#45]
When building with `-j auto`  a duplicate warning is thrown about the same file when nothing is actually duplicated

afaict it throws the warning for every invokation of httpdomain in our docs

typical warnings from our ci logs:

```console
WARNING: duplicate HTTP post method definition /reopen_logs in /source/generated/rst/operations/admin.rst, other instance is in /source/generated/rst/operations/admin.rst
WARNING: duplicate HTTP get method definition / in /source/generated/rst/operations/admin.rst, other instance is in /source/generated/rst/operations/admin.rst
WARNING: duplicate HTTP get method definition /help in /source/generated/rst/operations/admin.rst, other instance is in /source/generated/rst/operations/admin.rst
WARNING: duplicate HTTP get method definition /certs in /source/generated/rst/operations/admin.rst, other instance is in /source/generated/rst/operations/admin.rst
```

not sure if just preventing the warning when both sources are the same would work (or whether that would actually suppress real duplicates)

if this is a reasonable fix im happy to pr

**Comment by phlax** [comment]
@benjaoming i believe it was fixed in https://github.com/sphinx-contrib/httpdomain/pull/59 - we are now using this plugin with `-j auto` and no custom hacks (iirc)

**Comment by phlax** [comment]
if you can confirm i will close this issue

**Comment by benjaoming** [comment]
Yes, I just noticed, checking out 1.8.1 now, 2 minutes and I'll be back :)

**Comment by benjaoming** [comment]
I was on 1.8.0 btw...

**Comment by benjaoming** [comment]
Yes, confirming that I reproduced this issue and upgrading to 1.8.1 made it go away :100:

**Comment by benjaoming** [comment]
Thanks :pray:
