### ISSUE TITLE
force_decode is no longer available in Sphinx 4.0.0

### ISSUE THREAD

**Issue by Zlopez** [sphinx-contrib/httpdomain#46]
Hi,

today I tried to update to sphinx 4.0.0 and the build of doc failed on:
```
Extension error:
Could not import extension sphinxcontrib.autohttp.flask (exception: cannot import name 'force_decode' from 'sphinx.util' (/var/home/zlopez/git/anitya/.tox/docs/lib/python3.9/site-packages/sphinx/util/__init__.py))
```

It seems that `force_decode` is deprecated from Sphinx 2.0 and it is removed completely in 4.0. See https://www.sphinx-doc.org/en/master/extdev/deprecated.html

**Comment by stevepiercy** [comment]
The same issue appears in https://github.com/repoze/repoze.sphinx.autointerface/issues/16. I started a PR https://github.com/repoze/repoze.sphinx.autointerface/pull/17, but haven't had time to fix the remaining issues.

I could definitely use advice on how to replace `sphinx.ext.autodoc.AutoDirective` with `application.Sphinx.add_autodocumenter()` and for addressing an issue with `sphinx.theming.Theme.themes`.

**Comment by kasium** [comment]
Hi guys,
I also stumbled across this issue. Maybe it's worth to ask the sphinx developers how to fix the open issues?

**Comment by Zlopez** [comment]
The change is now reverted in 4.0.3 of sphinx. The `force_decode()` works again. See [changelog|https://github.com/sphinx-doc/sphinx/blob/4.0.x/CHANGES] for 4.0.3

**Comment by kloczek** [comment]
OK.
Thx :)

**Comment by kloczek** [comment]
Just tested that. With 4.0.3
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.0.3
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-sphinxcontrib-httpdomain.3 { } done
build succeeded.
```
One more time thank you to let me know :)

**Comment by stevepiercy** [comment]
I would suggest that you reopen this issue. `force_decode()` will become a problem when Sphinx 5.0 is released because its usage is still deprecated. The change note is a little misleading because the contributor used the term "during" instead of "until". See: https://github.com/sphinx-doc/sphinx/pull/9326#issuecomment-873383816

> This reverts the removal and extends its deprecation period to 5.0.0. I hope it helps users of these extensions.

**Comment by kasium** [comment]
I'm also happy to support here, but yes, this will become an issue again in Sphinx 5

**Comment by mcepl** [comment]
I happily accept that [this patch](https://github.com/sphinx-contrib/httpdomain/files/6793579/missing_force_decode.patch.txt) is not the greatest achievement of the computer science, but it seems to do the job, and it allows me to build httpdomain package for openSUSE with different versions of Sphinx.

**Comment by danc86** [comment]
PR #49 seems to be a reasonable solution to this (just remove all usages of `force_decode` because they should not be needed).
