### ISSUE TITLE
<autoflask>:1:Problem in http domain: field is supposed to use role 'obj', but that role is not in the domain.

### ISSUE THREAD

**Issue by Zlopez** [sphinx-contrib/httpdomain#53]
Hi,

I recently started getting this error when building sphinx documentation. You can see the log from the build [here](https://fedora.softwarefactory-project.io/zuul/build/24bd938e0c6848d1b404897e03077808/log/job-output.txt#275).

The sphinx config can be found [here](https://github.com/fedora-infra/anitya/blob/c3834862d629e0a4735092a4abc0a3059f382393/docs/conf.py)

And the whole docs is [here](https://github.com/fedora-infra/anitya/tree/c3834862d629e0a4735092a4abc0a3059f382393/docs)

The autoflask usage is only in [this rst file](https://github.com/fedora-infra/anitya/blob/c3834862d629e0a4735092a4abc0a3059f382393/docs/api.rst)

I'm not sure how to fix this issue, because it doesn't seem to refer to anything in the documentation itself.

**Comment by cblegare** [comment]
Looks like there is a related PR: #51

**Comment by Zlopez** [comment]
Any ETA for releasing this fix?

**Comment by LefterisJP** [comment]
+1 Would also love to know when this will be included in a release as it affects our project. Happy to see it's already handled though :smile:

**Comment by LefterisJP** [comment]
Thanks a lot @ashb
