### ISSUE TITLE
Tornado >=4.5 support still broken in some cases

### ISSUE THREAD

**Issue by robertdzeigler** [sphinx-contrib/httpdomain#7]
auto tornado assumes "handler_class" and "regex" properties on the "spec" objects, consistent with the URLSpec object. However, in Tornado 4.5, routes may be rules (and URLSpec is a subclass of rule), and rules have "target" and "matcher" properties (with regex @ matcher.regex).

**Comment by mtrienis** [comment]
+1

**Comment by dahlia** [comment]
Fixed by the PR #11.
